#!/usr/bin/bash

export MOZ_USE_XINPUT2=1
export MICRO_TRUECOLOR=1

export VISUAL="codium -w"
export EDITOR="nano"

export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.spicetify"

export GTK_USE_PORTAL=1
