[".config/spicetify/CustomApps/marketplace"]
    type = "archive"
    url = "https://github.com/spicetify/spicetify-marketplace/archive/dist.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/spicetify/Themes/Nordify"]
    type = "archive"
    url = "https://github.com/Tuuuukka/Nordify/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
