#!/usr/bin/bash

export BASHDOTDIR=$HOME/.bash

[ -f "$BASHDOTDIR/.bashrc" ] && . $BASHDOTDIR/.bashrc
[ -f "$BASHDOTDIR/env.private" ] && . $BASHDOTDIR/env.private
[ -f "$BASHDOTDIR/app-env" ] && . $BASHDOTDIR/app-env
[ -f "$BASHDOTDIR/env" ] && . $BASHDOTDIR/env
[ -f "$BASHDOTDIR/aliases" ] && . $BASHDOTDIR/aliases
[ -f "$BASHDOTDIR/aliases.private" ] && . $BASHDOTDIR/aliases.private


[ -f /usr/share/bash-completion/bash_completion ] && source /usr/share/bash-completion/bash_completion
[ -f "/etc/profile.d/devkit-env.sh" ] && source /etc/profile.d/devkit-env.sh
[ -f "$HOME/.nvm/nvm.sh" ] && source ~/.nvm/nvm.sh

# pnpm
export PNPM_HOME="/home/botato/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end