#!/bin/sh

revert() {
	xset dpms 0 0 0
}

trap revert HUP INT TERM

xset +dpms dpms 5 5 5


img=/tmp/i3lock.png
scrot -o $img

convert $img -colorspace Gray $img
convert $img -scale 10% -scale 1000% $img


playerctl stop

i3lock -n -i $img

revert
