#!/usr/bin/env bash
RAND=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 6 | head -n 1)
unbuffer $HOME/.local/bin/b2 upload-file AAGaming-Public $1 "ss/${RAND}.${1##*.}" | unbuffer -p sed -nr 's/.*( |^)([0-9]+)%.*/\2/p' | zenity --progress --text="Uploading..." --auto-close
/usr/bin/copyq copy "https://img.bigdumb.gq/ss/${RAND}.${1##*.}" > /dev/null
notify-send -t 5000 -u low "Done, link is https://img.bigdumb.gq/ss/${RAND}.${1##*.}" > /dev/null
echo "https://img.bigdumb.gq/ss/${RAND}.${1##*.}"
echo "https://fakedeleteurl.yes"
