#!/bin/bash

if [ -z "$GITHUB_API_HOST" ]; then
	GITHUB_API_HOST="https://api.github.com"
fi

if [ -z "$1" ]; then
	echo "No repository provided."
	exit 1
fi

path="$GITHUB_API_HOST/repos/$1"

repoSizeInKb="$(curl -sL $path | jq -r '.size')"

echo "Results for $1"
echo "Kilobytes: $repoSizeInKb"
echo "Megabytes: $(echo $repoSizeInKb | awk '{printf($1/1e3)}')"
echo "Gigabytes: $(echo $repoSizeInKb | awk '{printf($1/1e6)}')"
echo "Terabytes: $(echo $repoSizeInKb | awk '{printf($1/1e9)}')"
