#!/usr/bin/env bash

set -e

cp /dev/stdin /tmp/image.png

$HOME/scripts/image-b2 /tmp/image.png
# Script already provides regular url, provide fake deletion url
echo "https://fakedeleteurl.yes"

rm /tmp/image.png
